### ISSUE TITLE
Output format should be compatible with glidertools

### ISSUE THREAD

**Issue by ocefpaf** [ioos/gliderpy#2]
@callumrollo mentioned this in out meeting yesterday. It would be nice to get the specs of that format.

**Comment by callumrollo** [comment]
Looks like glidertools use very simple 1D numpy arrays internally; so, storing our data in a pandas dataframe should be fine

https://github.com/GliderToolsCommunity/GliderTools/blob/master/notebooks/Demo_GT.ipynb

**Comment by ocefpaf** [comment]
Great! We can add a notebook with a glider search and then a processing with it.

**Comment by ocefpaf** [comment]
> Great! We can add a notebook with a glider search and then a processing with it.

I'm not familiar with `glidertools` but, after checking that notebook, it doesn't really make sense for us to add an example b/c our data, in theory, was already processed, QA/QC'ed, etc. Glidertools happen before the data were added to the server.
