### ISSUE TITLE
Add kwargs for the plotting routines

### ISSUE THREAD

**Issue by ocefpaf** [ioos/gliderpy#21]
We have some pre-defined options but we should make them "customizable."

I'll remove the `cmap` definition for now in a new PR just to get the notebooks running.

**Comment by celestinelindarto** [comment]
Hi @ocefpaf,

Is there any particular customization that needs to be implemented for the gliderpy library?

Please let me know.

Thank you.

**Comment by ocefpaf** [comment]
@celestinelindarto I need to refresh my mind but, without looking at the code, I recall we had some hard-coded defaults that could use some user input instead. Take a quick look at the current plotting code and let me know what you think.

**Comment by celestinelindarto** [comment]
Ok, thank you for getting back to me @ocefpaf.

**Comment by ocefpaf** [comment]
This one was already done.
