### ISSUE TITLE
Test request to server

### ISSUE THREAD

**Issue by callumrollo** [ioos/gliderpy#35]
Currently no data is fetched during the testing process. I understand data fetching does not actually occur until the `to_pandas` method is called. We should test this.

**Comment by ocefpaf** [comment]
Sure. There are a few things we need to consider when testing requests online:

1. should we mock it or test against the server?
2. if not mocking, which is usually easier, the goal of the test is to check the code, the server, or both?
3. when the goal is to test only the code we can use `pytest-vcr`. I just implemented it in erddapy and should be relatively easy to port the change here.
4. when the goal is to test the server we would be better off with a service that checks if the server is working. Argopy just implemented something like that, see https://github.com/euroargodev/argopy-status and https://argopy.statuspage.io/
