### ISSUE TITLE
Add ERDDAP graph responses

### ISSUE THREAD

**Issue by ocefpaf** [ioos/gliderpy#36]
Use @kerfoot gdutils plotting functions as a starting point.

**Comment by callumrollo** [comment]
I see you've encouraged @kerfoot to make gdutils a Python package. Is this still on the roadmap? It looks like it would work well as-is with gliderpy, not sure reimplementing it here would be beneficial

**Comment by ocefpaf** [comment]
> I see you've encouraged @kerfoot to make gdutils a Python package. Is this still on the roadmap? It looks like it would work well as-is with gliderpy, not sure reimplementing it here would be beneficial

Probably not. My guess is that @kerfoot would be OK with us just "porting" the plotting parts to this library instead to reduce the maintenance burden in gdutils.

**Comment by kerfoot** [comment]
@ocefpaf I'm an fully ok with that.  With everything else I've got on my plate these days, it would be a while before I can get back to this.

**Comment by ocefpaf** [comment]
We have some basic Python plotting. Maybe we could add a ERDDAP plotting interface in erddapy and expose it here but I'm not sure it is worth the effort at the moment. Closing this as "wont't fix" for now.
