### ISSUE TITLE
Friendly server names

### ISSUE THREAD

**Issue by callumrollo** [ioos/gliderpy#38]
So a user can specify any of:

- http://www.ifremer.fr/erddap
- http://www.ifremer.fr/erddap/index.html
- ifremer
- IFREMER

and get the correct response from GliderPy

**Comment by ocefpaf** [comment]
Take a look at https://github.com/ioos/erddapy/blob/master/erddapy/erddaps.json. We don't need that JSON, that is needed in erddapy b/c we use the awesome ERDDAP list. We can do a dict in a .py file.

PS: BTW, I don't do a case normalization in erddapy, easy PR in case you want to send it ;-p

**Comment by callumrollo** [comment]
Great! I'll check it out this evening :)

**Comment by callumrollo** [comment]
Implemented in #41
