### ISSUE TITLE
Move all plotting methods to use pandas-flavor

### ISSUE THREAD

**Issue by ocefpaf** [ioos/gliderpy#44]
xref.: https://github.com/Zsailer/pandas_flavor

**Comment by Harish-2003** [comment]
Is this issue solved?

**Comment by ocefpaf** [comment]
> Is this issue solved?

This issue is part of Google Summer of Code 2024. If you are interested you can find more information at https://github.com/ioos/gsoc/issues/43

**Comment by ocefpaf** [comment]
This is 80% done. Closing it as we will complete before GSoC is over.
