### ISSUE TITLE
Cache the request locally...

### ISSUE THREAD

**Issue by ocefpaf** [ioos/gliderpy#9]
...and create some sort of hash for reproducibility. That way we can know if the same request yielded different data.

**Comment by callumrollo** [comment]
What is a "has for reproducibility"? I will use lru to cache stuff as best I can

**Comment by ocefpaf** [comment]
> What is a "has for reproducibility"? I will use lru to cache stuff as best I can

It was supposed to read `hash`. I just updated it. Typing with one hand and holding the baby in another one has some consequences ;-p

**Comment by callumrollo** [comment]
Ah cool, working those ninja baby juggling skills :P 

lru first then I'll look up hashes
