### ISSUE TITLE
Have been facing key errors while using the function  plot_track which is present in plotters.py file 

### ISSUE THREAD

**Issue by Harish-2003** [ioos/gliderpy#90]
![image](https://github.com/ioos/gliderpy/assets/76206815/bf276183-6fbb-4b4a-9440-d18b597de754)
this issue is adressed at pr https://github.com/ioos/gliderpy/pull/86
and also at pr https://github.com/ioos/gliderpy/pull/89 (in this pull request more info about readme file is added and also an label track is added

**Comment by ocefpaf** [comment]
Hi @Harish-2003! Thanks for the issue and the PRs. We'll check them shortly. Note that, when pasting, code please do not use images b/c they make it quite hard to copy-n-paste for testing. They are also hard to search!

**Comment by Harish-2003** [comment]
```python
from gliderpy.fetchers import GliderDataFetcher
from matplotlib import pyplot as plt
from gliderpy.plotters import plot_track

glider_grab = GliderDataFetcher()

glider_grab.fetcher.dataset_id = "whoi_406-20160902T1700"

df = glider_grab.to_pandas()

plot_track(df)
```
this is the code which i was trying to run.... 
and yea sure will not use images from this time @ocefpaf

**Comment by ocefpaf** [comment]
We should probably address this by figuring out why the units were dropped in the column labels and re-add them. My guess is that the response was changed from csvp to csv somewhere.

**Comment by ocefpaf** [comment]
I believe this was fixed. This code was all re-written and the tests are passing. Closing this.
